// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7znUHopLzITkiX_3elc_hjGf8m78hrUg',
    appId: '1:80241012509:web:6e3ff41e5237f64db1bbf4',
    messagingSenderId: '80241012509',
    projectId: 'logpage-9aeb7',
    authDomain: 'logpage-9aeb7.firebaseapp.com',
    storageBucket: 'logpage-9aeb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI8K2u3pfF6EpO-zmitUEsDgJiyoYYoWk',
    appId: '1:80241012509:android:c62b235c3c070ac5b1bbf4',
    messagingSenderId: '80241012509',
    projectId: 'logpage-9aeb7',
    storageBucket: 'logpage-9aeb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRlka_nf3tWZb7ao0AxGWHQSD-Mpq28FQ',
    appId: '1:80241012509:ios:b35059f97871e0a3b1bbf4',
    messagingSenderId: '80241012509',
    projectId: 'logpage-9aeb7',
    storageBucket: 'logpage-9aeb7.appspot.com',
    androidClientId: '80241012509-1eqi0s3hffimpuv85qn5jam8ffo7l3co.apps.googleusercontent.com',
    iosClientId: '80241012509-tc099dthrolg83mg807o1fu03eb7ps3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRlka_nf3tWZb7ao0AxGWHQSD-Mpq28FQ',
    appId: '1:80241012509:ios:9120589db52ef3c0b1bbf4',
    messagingSenderId: '80241012509',
    projectId: 'logpage-9aeb7',
    storageBucket: 'logpage-9aeb7.appspot.com',
    androidClientId: '80241012509-1eqi0s3hffimpuv85qn5jam8ffo7l3co.apps.googleusercontent.com',
    iosClientId: '80241012509-m520h8gn42vrssgba413buclf0a42tuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}