// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCawwDlOoXBi0Kh8Y_EBK05UfK0aS9rL-U",
  authDomain: "recipe-app-8e3a1.firebaseapp.com",
  projectId: "recipe-app-8e3a1",
  storageBucket: "recipe-app-8e3a1.firebasestorage.app",
  messagingSenderId: "476461090974",
  appId: "1:476461090974:web:0b516f7131fdc502bb138f"
  );






static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyCaithTVhl80gigSr7Y7W_1H0ARUVCmwfc',
  appId: '1:476461090974:android:71d6e9a58f6ba4a9bb138f',
  messagingSenderId: '476461090974',
  projectId: 'recipe-app-8e3a1',
  storageBucket: 'recipe-app-8e3a1.firebasestorage.app',
);



static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyCSwziz-36RwjHYaOF73XB6DO-XI_JN984',
  appId: '1:476461090974:ios:5ecef1cbd014662dbb138f',
  messagingSenderId: '476461090974',
  projectId: 'recipe-app-8e3a1',
  storageBucket: 'recipe-app-8e3a1.firebasestorage.app',
  iosBundleId: 'com.htm.RecipeAppIos',
);



}