name: Deploy Recipe Application Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web
      run: flutter build web --release
      
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Remove existing remote and add new one with token
        git remote remove origin || true
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/harrytmiller/recipe_application.git
        
        # Create a new orphan branch for gh-pages
        git checkout --orphan gh-pages
        
        # Remove all files from this branch
        git rm -rf .
        
        # Copy the built web files to this branch
        cp -r build/web/* .
        
        # Add a .nojekyll file to bypass Jekyll processing
        touch .nojekyll
        
        # Add and commit the web files
        git add .
        git commit -m "Deploy Flutter web app"
        
        # Push to gh-pages branch
        git push origin gh-pages --force
        
        # Switch back to main branch
        git checkout main
        
    - name: Output deployment URL
      run: |
        echo "🚀 Deployment complete!"
        echo "📱 Your app is live at: https://harrytmiller.github.io/recipe_application/"